language: bash
script:
- bash script.sh
notifications:
  slack:
    template:
      - "Build:  <%{build_url}|#%{build_number}>"
      - "Repo/Branch: %{repository_slug}@%{branch}"
      - "Author: %{author}" 
      - "Summary: %{result} in %{duration}"
      - "Commit (<%{compare_url}|%{commit}>): %{commit_message}"
    rooms:
      secure: j6vntFJ+5dWAA9H40/SCt1OGXVUzwHujRCT2SeGOUGwsPuNdjbTmANYv752JKIj/1RvX51R/N6b6Vptdn23uk02I3H759Zcu0sd7YTqLX6n+gVjYRjJ6J9SLTOW7Es6kmtB0lPbqyqhnQq0AZmwv9n+iSwvrYb1c8oOvdWIYTput+8Ymr/1MIPIfJPoz3T1iae1ks60eflzUnFNEDV17HhavaFKtxEeGMXfTAFqavacPRBKFUWNoTj+JuhJEQVVZsAN71YvN9WNvSfpZggZP1t11ivDaYkLT5VcX3W3zBoBQnq0kZExO8Xvru5keLTfn2Ceh3paFxeAEuCXf6FSJTYfdN4Cha2hMRVX+rI3pNOkWBR26Krbli47P9xVdXYpSMdxsaYBW51yiyaLmXLbRJvCAtap1ih8x2YFz+dED8pUWXGsTBeY+2z6LWWXg/xyMh+HKD58TA2PaKxU2P+XWPm7PBXOmr9z/9tICZYXLKSIiIrWTGNrlE5Ugg13TzU88aUFNbGM7BUk1Us9GJutOJsRC8tR9k1SKzKbwoXw5NXqBZZwsgoFK3QZT/rgnere+jPQD53tHZ6BoGoLPTBR2NQTS9vgfMP0UhfVnBr09ZahVtjRxTykOg4eSWcQgAng2+RsTPjuz3LyqpcpFIcEmUkiDMrXw2qTf5KLUhpJ/UpY=
sudo: required
env:
  global:
    secure: c4++vCfXagefDECUZUZW0FvBA4xqokRIpLsVIZAmdbwO2sBtvbaYLTiJT24IyKi0Nd2J3/xGIN3xwzBUPDnws9WprWFY8C2bKA81ThnmLAJ0STyOgeLIDwnUHP7W0LNprM0g6Y6Gzc1Htr7Khn0X1ZZkzi1PeugwspTrpzP4abtTzT+lNI+8oVEism3Vfvr7QzB25TMWFFwZ3bry1+dfwtCL3Sh+AuRsrmxUj7yVmvbo3KDFGRQGTJQnB5w7QihyAGn4ZyEgWcNCHSuHkYkwhbiX3od+mL2Q1eNY2Tcj8Mrl30BrDA331TKU78m2KfIAsstxsbR1cHAwPIee6r5th4Yb5TnKp0N7yipKBaVFUPmE9pdi+aIa6qRj0JJyKfEzi9MKmJuUtv+TG+tOdIoU6IVGGONQUQDmpt06J/2JIFHwBmQ/R01wTYIesXUQFpAt2n6U9aXavEBzDo+2bfORN3N7XEWTagqApYM8aEiLfVWPmNbCXX1h8bJ83tSBIedXxdA73mIAT6Ypr4mxwUYkuEVxjLl0wC1+fgz/6P5ypKDiJctofDQQ2jYXGWGYwFPvkyRWxSyYQ7p9r3J91dh9zwymz2a+sl+B5mv+ewI1fXqwX8ljzliB5dzp1hqrzrYOFBNEI8RH6EtBZeBtghk88da7mHgRv4bBMw9vZyST9pk=
