language: bash
script:
- bash script.sh
#notifications:
#  slack:
#    template:
#      - "Build:  <%{build_url}|#%{build_number}>"
#      - "Repo/Branch: %{repository_slug}@%{branch}"
#      - "Author: %{author}" 
#      - "Summary: %{result} in %{duration}"
#      - "Commit (<%{compare_url}|%{commit}>): %{commit_message}"
#    rooms:
#      secure: j6vntFJ+5dWAA9H40/SCt1OGXVUzwHujRCT2SeGOUGwsPuNdjbTmANYv752JKIj/1RvX51R/N6b6Vptdn23uk02I3H759Zcu0sd7YTqLX6n+gVjYRjJ6J9SLTOW7Es6kmtB0lPbqyqhnQq0AZmwv9n+iSwvrYb1c8oOvdWIYTput+8Ymr/1MIPIfJPoz3T1iae1ks60eflzUnFNEDV17HhavaFKtxEeGMXfTAFqavacPRBKFUWNoTj+JuhJEQVVZsAN71YvN9WNvSfpZggZP1t11ivDaYkLT5VcX3W3zBoBQnq0kZExO8Xvru5keLTfn2Ceh3paFxeAEuCXf6FSJTYfdN4Cha2hMRVX+rI3pNOkWBR26Krbli47P9xVdXYpSMdxsaYBW51yiyaLmXLbRJvCAtap1ih8x2YFz+dED8pUWXGsTBeY+2z6LWWXg/xyMh+HKD58TA2PaKxU2P+XWPm7PBXOmr9z/9tICZYXLKSIiIrWTGNrlE5Ugg13TzU88aUFNbGM7BUk1Us9GJutOJsRC8tR9k1SKzKbwoXw5NXqBZZwsgoFK3QZT/rgnere+jPQD53tHZ6BoGoLPTBR2NQTS9vgfMP0UhfVnBr09ZahVtjRxTykOg4eSWcQgAng2+RsTPjuz3LyqpcpFIcEmUkiDMrXw2qTf5KLUhpJ/UpY=
sudo: required
env:
 global:
      secure: "nremVPpkAeLK7t1NSliGCliLz8Rg+ZPR5/yKPEQJUdfTPnD+2Q2eHlqD5GVZkRiSBeGiB8mDlf/rpcURcJIHD4HxKra4k/CWWQtyr6jmuAa+UJ0h4PkkFkzqtBDd1E+u7W78vy3fi3aBaAA1/uzegfkMRv/p5KFuewHk9Z1OurP5fnPvlsjS7hvfEhCRQK/ybW9fBjloN7Yivmqt9i+vznTSKwJAz4hCmMonJLu2rDASlC2ZQXqB5U00Ifw+xJyuVB3d9m9IphufCD6CNrKb/X3zRIcu9zr5btLN3LZ4IsaDtxHf4ZK94IwBddIJ++aR8gmVodohRSYDEKuJLXx9+bY7GAm6cUKdpmq16mH0TQjh9/r2Zp+TpchArfG8aWX6iKL5+C5evKcXdA2j5pJUj82k1Kg7tjCfUg7ublMTZ8S1wzZkvdI6myqnljWXzAvOHQx4Ph/MYFdUdecwH+ov7GpyMnRSwjIAuMuSRIjKflyB+4VHU4WtOUkaW9ssto/FnMCO6+JKfvq9FwzjEv+PfHdGpl1ngO3CTXNf1FVKfrJJA5Yqbg2fAQjYH3y91g4nmwdVaUMg958Mo7zQqL4cWqUDqYeOOyz6/E04ioekYnjJmurt8AynBd1s/vJ6ddoVitJ25SYo7MAUUrtjWVHpefwWR9ita1VJacYkxDkINAc="
