language: bash
install: true
script: 
  - ./mvnw clean install
  - bash script.sh
#notifications:
#  slack:
#    template:
#      - "Build:  <%{build_url}|#%{build_number}>"
#      - "Repo/Branch: %{repository_slug}@%{branch}"
#      - "Author: %{author}" 
#      - "Summary: %{result} in %{duration}"
#      - "Commit (<%{compare_url}|%{commit}>): %{commit_message}"
#    rooms:
#      secure: j6vntFJ+5dWAA9H40/SCt1OGXVUzwHujRCT2SeGOUGwsPuNdjbTmANYv752JKIj/1RvX51R/N6b6Vptdn23uk02I3H759Zcu0sd7YTqLX6n+gVjYRjJ6J9SLTOW7Es6kmtB0lPbqyqhnQq0AZmwv9n+iSwvrYb1c8oOvdWIYTput+8Ymr/1MIPIfJPoz3T1iae1ks60eflzUnFNEDV17HhavaFKtxEeGMXfTAFqavacPRBKFUWNoTj+JuhJEQVVZsAN71YvN9WNvSfpZggZP1t11ivDaYkLT5VcX3W3zBoBQnq0kZExO8Xvru5keLTfn2Ceh3paFxeAEuCXf6FSJTYfdN4Cha2hMRVX+rI3pNOkWBR26Krbli47P9xVdXYpSMdxsaYBW51yiyaLmXLbRJvCAtap1ih8x2YFz+dED8pUWXGsTBeY+2z6LWWXg/xyMh+HKD58TA2PaKxU2P+XWPm7PBXOmr9z/9tICZYXLKSIiIrWTGNrlE5Ugg13TzU88aUFNbGM7BUk1Us9GJutOJsRC8tR9k1SKzKbwoXw5NXqBZZwsgoFK3QZT/rgnere+jPQD53tHZ6BoGoLPTBR2NQTS9vgfMP0UhfVnBr09ZahVtjRxTykOg4eSWcQgAng2+RsTPjuz3LyqpcpFIcEmUkiDMrXw2qTf5KLUhpJ/UpY=
sudo: required

after_success:
  - push.sh
env:
  global:
    secure: nJ9CPt59zMpS6Xj6XCk4kgt0MmViT/eEkKrFsyBBEoceS5K1xPbvT2SQKP3Vl5dOhKrtfxHQHynAXrt+aztFxVSjbsrQ/MvEa/oT/1qDAYSnoMj1HbXCosfyW2fvDbbqTiSYu4w1jvxHu35qC4ksVKOUgnBgk2DwT9zTFuw/0jNQEcSDf4F+8XURAIj9lOGJffSksDDbg0+YdBTsVWvmxhXuXPAfHf04nnsW7qUNhI6IkxXNiNVU+XSU+89MOLRA9GAiMB9pefFMVS0Nwxthv3D3h9BhuzkOUJNEf41IZMtYQgPPfd40/XxPf1UQ/pEuOrVPHjI2YKuCh8B4bJTIi7Y5TwMfMxjhl8NfW9jG7/r4JuIEFPsQTtbntBrvmnshhX0ExRG+0wn4Y92mmfYtiOeBRyqyKmZlSjoWoxwUR4jdctJO7pAewrLUmXxZ6S5NI6N6ibugVZjPJ2rbzLZd5qoKPf20B0kR3YQpzP0gxZWRcQ4H9Xy37H6km94GsMbbPEvbstXtA0JpjOalb+eWjmviQH5QnjlHUUKU9uZhf7iVxJ3h2TZ3WHzaXMsOfaOklvKOMBgE2qeUMb3CCLSfhcfCoRYXOjv9UFq/nKrxSrfaQjWDF9QHZfwBLt6mnLFJFl89Ta5ze/tEygsBQKib0q/wodxpxurO3o2YL6jcZNQ=
