language: bash
script:
- bash script.sh
#notifications:
#  slack:
#    template:
#      - "Build:  <%{build_url}|#%{build_number}>"
#      - "Repo/Branch: %{repository_slug}@%{branch}"
#      - "Author: %{author}" 
#      - "Summary: %{result} in %{duration}"
#      - "Commit (<%{compare_url}|%{commit}>): %{commit_message}"
#    rooms:
#      secure: j6vntFJ+5dWAA9H40/SCt1OGXVUzwHujRCT2SeGOUGwsPuNdjbTmANYv752JKIj/1RvX51R/N6b6Vptdn23uk02I3H759Zcu0sd7YTqLX6n+gVjYRjJ6J9SLTOW7Es6kmtB0lPbqyqhnQq0AZmwv9n+iSwvrYb1c8oOvdWIYTput+8Ymr/1MIPIfJPoz3T1iae1ks60eflzUnFNEDV17HhavaFKtxEeGMXfTAFqavacPRBKFUWNoTj+JuhJEQVVZsAN71YvN9WNvSfpZggZP1t11ivDaYkLT5VcX3W3zBoBQnq0kZExO8Xvru5keLTfn2Ceh3paFxeAEuCXf6FSJTYfdN4Cha2hMRVX+rI3pNOkWBR26Krbli47P9xVdXYpSMdxsaYBW51yiyaLmXLbRJvCAtap1ih8x2YFz+dED8pUWXGsTBeY+2z6LWWXg/xyMh+HKD58TA2PaKxU2P+XWPm7PBXOmr9z/9tICZYXLKSIiIrWTGNrlE5Ugg13TzU88aUFNbGM7BUk1Us9GJutOJsRC8tR9k1SKzKbwoXw5NXqBZZwsgoFK3QZT/rgnere+jPQD53tHZ6BoGoLPTBR2NQTS9vgfMP0UhfVnBr09ZahVtjRxTykOg4eSWcQgAng2+RsTPjuz3LyqpcpFIcEmUkiDMrXw2qTf5KLUhpJ/UpY=
sudo: required
env:
  global:
    secure: rQewRP5k2MMxOTGhniUmqVYBRdM9cv7YwQnMf/W7Ge2q+OyBAmzYzfrcS70IjoUYFYR2r597ojz63hytvoEb4y+igj9lBZ/76viti+LDpzMIjwBnH7OF36n84sUwDlCvSYGd2ZPEGeZvm3vd58ytn4KNCkVUPEKX5U0mOFvc5KfupDfT2kFKIabzHdDYvSk4UWnRK8TuU6gwhsiuRAB9pCJHOUcy6wHOq9VA7TWQFFctTK6C+Sb4pZliMhDWYAheevCSwRkcBCDXODZNBYXEQU52OyuE1W+huVGXBLdUzeKOUfXbZBzMa6aWVQRTrxLwKCo1KMvxn9p9W4fYHMNVDq4gIIAhb+sEsYjXO/EDjhuhXFqTjgIsVzWuGjvpZ9mrc0TfSg9bQVERE+O3tVeaYh7PwMbWAsKR/BbKFPcYp1du3OEmTU030wLR2twcVURUthNC6HJNE+qCddvPVigKjDn4JLs76YxVAjQoE1RJsAdW6BGz3kH6rVCC7wZEoi7akfEJzXspqPrMAUXF8qOG0DnPEoHq+wZ4AaaLcxNnKK8FbUUQJM6gZSiCYYeVkHgCf6nyz33+VI7Z7x4iX2DH3Bas16NsKb9Fx+8BdeGy+nXP6IfH70PYzuNwZmj/lkiP6bjpeEGlRIKWOpy13OFWckl2zd0a4Vi8JnQcf5cFgGA=
after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    # This generates a `web` directory containing the website.
    make web
    cd web
    git init
    git add *
    git -c user.name='travis' -c user.email='travis' commit -m init
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://Ahmad-Ayyoub:$GITHUB_API_KEY@github.com/Ahmad-Ayyoub/draft-guide-microprofile-rest-client &2>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
